services:
  - type: web
    name: villen-music-backend
    env: python
    region: singapore
    buildCommand: ./backend/build.sh
    startCommand: cd backend && gunicorn core.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
